### ISSUE TITLE
Api help

### ISSUE THREAD

**Issue by Tetous** [system32uwu/sushi-night#3]
Im looking to srap this site and I need help. 
https://animek.fun/
How would you scrape this?
When you have time please tell me how you did it and the step it took to get there.

**Comment by system32uwu** [comment]
Hello, this is project doesn't do web scraping, it fetches streaming links for the episodes requested using sushi-night-backend.

The projects you are looking for are:
[sushi-night-backend](https://github.com/system32uwu/sushi-night-backend), which uses [animu-desu](https://github.com/system32uwu/animu-desu) to do it.

animu-desu is a library, which you can use in a node environment (it scrapes gogoanime using [cheerio](https://github.com/cheeriojs/cheerio)).

sushi-night-backend is an express app that has the routing already done (meaning that you can make GET requests to the endpoints of the app).

You can clone sushi-night-backend, cd into it, run `yarn start` and then in your browser go to localhost:3000, all the api endpoints will be listed there.

I'm not planning on adding any other source at the moment, but maybe I'll add 9anime due to it being the biggest anime library at the moment. I'm for sure going to develop a webtorrent app though, I've been torrenting for the last month and it's been way better than streaming.

If your issue is not related to the project I prefer to talk via Discord or something like it.
